# Generated by Django 3.0.4 on 2020-05-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeding date')),
                ('support', models.CharField(choices=[('P', 'Playstation'), ('N', 'Nintendo'), ('X', 'Xbox')], default='P', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Game')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
