# Generated by Django 3.0.4 on 2020-05-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_supported'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supported',
            new_name='Supporting',
        ),
    ]
