# Generated by Django 3.0.4 on 2020-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200506_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='toys',
            field=models.ManyToManyField(to='main_app.Award'),
        ),
    ]
