# Generated by Django 3.0.4 on 2020-05-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_toys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='toys',
            new_name='awards',
        ),
    ]
